/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_flyscale_testforffmpeg_NativeAPI */

#ifndef _Included_com_flyscale_testforffmpeg_NativeAPI
#define _Included_com_flyscale_testforffmpeg_NativeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_flyscale_testforffmpeg_NativeAPI
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_testforffmpeg_NativeAPI_stringFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_flyscale_testforffmpeg_NativeAPI
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_testforffmpeg_NativeAPI_urlprotocolinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_flyscale_testforffmpeg_NativeAPI
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_testforffmpeg_NativeAPI_avformatinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_flyscale_testforffmpeg_NativeAPI
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_testforffmpeg_NativeAPI_avcodecinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_flyscale_testforffmpeg_NativeAPI
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_flyscale_testforffmpeg_NativeAPI_avfilterinfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
